// packages/core/src/validation.js — validation helpers extracted from index.mjs
// Re-exported from the monolith until implementations are moved here.
// This module documents the validation function group for future extraction.

export {
  assertLocalFilePath,
  assertLocalJsonFilePath,
  validateManifest,
  validateTask,
  supportedTaskCapabilityScopes,
  isSupportedPermissionScope,
  normalizeCapabilities,
  resolveTaskCapabilities,
  validateApprovalReviewArtifactVersion,
  classifyApprovalReviewArtifactCompatibility,
  classifyArtifactSchemaMetadata,
  buildSchemaMigrationMetadataRecord,
  digestApprovalReviewArtifact,
  buildReviewArtifactAttestationPlan,
  buildMigrationAttestationDisplaySummary,
  normalizeApprovalReviewArtifactForDisplay,
  buildApprovalReviewArtifactDisplaySummary,
  validateApprovalReviewArtifact,
  validateSessionEvent,
  validateSessionTranscript,
  classifySessionTranscript,
  buildSessionTranscriptSummary,
  explainSessionTranscript,
  classifySessionTranscriptCompatibility,
  buildSessionTranscriptMigrationMetadata,
  buildSessionTranscriptDisplaySummary,
  explainSessionTranscriptCompatibility,
  classifyHostPolicyReviewRecordCompatibility,
  normalizeHostPolicyReviewRecordForDisplay,
  buildHostPolicyReviewRecordDisplaySummary,
  compareHostPolicyReviewRecords,
  formatHostPolicyReviewRecordComparisonJson,
  compareApprovalReviewArtifacts,
  formatSessionEventsJsonl,
  formatJsonlWholeLinesForReview,
  validateJsonlWholeLineBundle,
  redactStderrDiagnosticForReview,
  classifyRedactionSafety,
  formatStdioFramingRedactionContractJsonForReview,
  classifyTranscriptReplayCompatibilityForReview,
  formatTranscriptPersistenceContractJsonForReview,
  formatTranscriptReplayContractJsonForReview,
  formatTranscriptReplayCompatibilityRecordJsonForReview,
  classifyFailureAuditRecordForReview,
  formatFailureAuditRecordJsonForReview,
  readApprovalPrerequisiteRecordsForReview,
  evaluateRuntimeApprovalPrerequisitesForReview,
  preflightApprovalPrerequisiteSourcesForReview,
  selectApprovalPrerequisiteSourcesForReview,
  bundleApprovalPrerequisiteSourcesForReview,
  consumeApprovalPrerequisiteBundleForReview,
  evaluatePrerequisiteIntegrationCheckpointForReview,
  platformFamilyForNodePlatform,
  manifestPathToUrl,
} from "./index.mjs";